# .streamlit/pages.toml

[[pages]]
path = "app.py"
name = "ğŸ  Home"

[[pages]]
path = "pages/Overview.py"
name = "ğŸ“Š Data Overview"

[[pages]]
path = "pages/Visualization.py"
name = "ğŸ“ˆ Visualizations"

[[pages]]
path = "pages/Search.py"
name = "ğŸ” Product Search"

[[pages]]
path = "pages/ModelTraining.py"
name = "ğŸ§  Model Training"

[[pages]]
path = "pages/Models.py"
name = "ğŸ“ Model Results"

[[pages]]
path = "pages/FakeDataImpact.py"
name = "ğŸ§ª Fake Data Impact"

[[pages]]
path = "pages/Conclusion.py"
name = "âœ… Conclusion"
